### PR TITLE
ESC-461 backlink does not go back to cya

### PR DESCRIPTION
**Pull request by sam-miele**

### CODE REVIEW

**Comment by priyankadhiman3006** [comment]
one quick question to clarify one thing. When the user is on CYA page , click on change link for the sector. On the sector page user click back link where should the user be redirected to?

**Comment by sam-miele** [comment]
The undertaking name page. But good to flag up - can @thebailers  confirm please?

**Comment by thebailers** [comment]
> 

It should go to the previous page in the journey - the undertaking name page.

**Comment by priyankadhiman3006** [comment]
> > 
> 
> It should go to the previous page in the journey - the undertaking name page.

Thanks 👍

**Review by priyankadhiman3006 — APPROVED** [review]

**Pull request merged**
